///Hive Types
const int HIVE_TYPE_ID_BOOK_VO=1;
const int HIVE_TYPE_ID_BOOK_CATEGORY_VO=2;
const int HIVE_TYPE_ID_RESULT_VO=3;
const int HIVE_TYPE_ID_SHELF_VO=4;
const int HIVE_TYPE_ID_GOOGLE_BOOK_VO=5;
const int HIVE_TYPE_ID_VOLUME_INFO_VO=6;
const int HIVE_TYPE_ID_IMAGE_LINKS_VO=7;


///Box Names
const String BOX_NAME_BOOK_VO="BOX_NAME_BOOK_VO";
const String BOX_NAME_BOOK_CATEGORY_VO="BOX_NAME_BOOK_CATEGORY_VO";
const String BOX_NAME_RESULT_VO="BOX_NAME_RESULT_VO";
const String BOX_NAME_SHELF_VO="BOX_NAME_SHELF_VO";